name: Continuous Integration

on:
  workflow_run:
    workflows: [ "Check suite" ]
    types:
        - completed
  workflow_dispatch:
  
jobs:
  continuous-integration:
  
    if: |
      github.repository == 'percyqaz/YAVSRG' &&
      github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Attempt fast-forward + push
      run: | 
        git remote add YAVSRG https://github.com/YAVSRG/YAVSRG
        git fetch YAVSRG
        git checkout main
        git merge develop --ff-only
        git push