name: Continuous integration

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
jobs:
  automated-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Everything must build
      run: dotnet build
        
    - name: Unit tests must pass
      run: |
        cd scripts
        chmod +x ./run_tests.sh
        ./run_tests.sh
        
    - name: Attempt fast-forward + push
      if: |
        github.repository == 'percyqaz/YAVSRG' &&
        github.ref == 'refs/heads/develop'
      run: | 
        git remote add YAVSRG https://github.com/YAVSRG/YAVSRG
        git fetch YAVSRG
        git checkout main
        git merge develop --ff-only
        git push
        
    - name: Notify of failure in main
      if: failure() && github.repository == 'YAVSRG/YAVSRG'
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DEV_WEBHOOK_URL }}
        content: |
          <@165506274820096000> You broke the build. Skill issue exists between chair and keyboard
